subscription_id      = "<YOUR_SUBSCRIPTION_ID>"
project_name         = ""
location             = "Sweden Central"
vm_size              = "Standard_B2als_v2"
admin_username       = "adminuser"
golden_image_version = "1.0.0"
ssh_public_key_path  = "../../environments/development/keys/adminuser-dev.pub"
