project_name        = "archie"
location            = "westeurope"
vnet_cidr           = "10.0.0.0/16"
subnet_cidr         = "10.0.1.0/24"
vm_size             = "Standard_B2s"
admin_username      = "archieadmin"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
